// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEoaT3yMMtp1fp3d0GWW3IjGg4sa4yDlw',
    appId: '1:682658252431:web:5905c728fd563a5ad412fa',
    messagingSenderId: '682658252431',
    projectId: 'd92-shift',
    authDomain: 'd92-shift.firebaseapp.com',
    storageBucket: 'd92-shift.appspot.com',
    measurementId: 'G-YMWT1PXC0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-_NPb5QqOrGu6dtTkEipKagq9F6ar1E',
    appId: '1:682658252431:android:096c5fd887c4d03cd412fa',
    messagingSenderId: '682658252431',
    projectId: 'd92-shift',
    storageBucket: 'd92-shift.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbLeqylpf0BnmxJRN1wkyj-aUXHs4D0l4',
    appId: '1:682658252431:ios:1738410e4b8c633cd412fa',
    messagingSenderId: '682658252431',
    projectId: 'd92-shift',
    storageBucket: 'd92-shift.appspot.com',
    iosClientId: '682658252431-h8c3q627dtmc5126381mgircegedjvl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.d92Shift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbLeqylpf0BnmxJRN1wkyj-aUXHs4D0l4',
    appId: '1:682658252431:ios:1738410e4b8c633cd412fa',
    messagingSenderId: '682658252431',
    projectId: 'd92-shift',
    storageBucket: 'd92-shift.appspot.com',
    iosClientId: '682658252431-h8c3q627dtmc5126381mgircegedjvl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.d92Shift',
  );
}
